# 网站基本信息 (新增部分)
title: 俄语大师
description: 专为中国人打造的免费俄语学习课程
lang: zh-CN

defaults:
  -
    scope:
      path: "**/*.html"
    values:
      layout: "default"

# 资源链接 (保持不变，确保图片能显示)
mediaurl: "https://media.githubusercontent.com/media/krisl/learnrussian.rt.com/master"
cssurl: "https://media.githubusercontent.com/media/krisl/learnrussian.rt.com/master/s/css/"
#baseurl: "/learnrussian.rt.com"
